"""Dodano client_log

Revision ID: 79ace028dc1e
Revises: 8bb75386b0ad
Create Date: 2025-06-13 20:01:29.982948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ace028dc1e'
down_revision = '8bb75386b0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('bed_time', sa.Time(), nullable=True),
    sa.Column('training', sa.String(length=1), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_log')
    # ### end Alembic commands ###
